apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: status-monitor-data
  namespace: status-monitor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
