"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-06-18

Baseline capturing the schema produced by the legacy create_all() path, so
existing databases can be stamped here and future migrations applied on top.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expected_status', sa.Integer(), nullable=True),
    sa.Column('dns_record_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traceroute_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_host', sa.String(length=200), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_hops', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('dns_result', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.create_index('ix_check_results_monitor_checked', ['monitor_id', 'checked_at'], unique=False)

    op.create_table('topology_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('x_position', sa.Float(), nullable=False),
    sa.Column('y_position', sa.Float(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traceroute_hops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('hop_number', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=200), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('is_timeout', sa.Boolean(), nullable=False),
    sa.Column('hop_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['traceroute_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topology_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['topology_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['topology_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topology_links')
    op.drop_table('traceroute_hops')
    op.drop_table('topology_nodes')
    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.drop_index('ix_check_results_monitor_checked')

    op.drop_table('check_results')
    op.drop_table('traceroute_runs')
    op.drop_table('monitors')
    # ### end Alembic commands ###
